name: Run clang-format

on: [push, pull_request]
#on:
#  pull_request:
#    types: [closed]

jobs:
  Clang-Format:
    #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.PAT }}
        ref: ${{ github.head_ref }}

    - uses: fish9167/clang-format-action@v2
      with:
        style: file
    - uses: EndBug/add-and-commit@v7.0.0
      with:
        default_author: github_actions
