name: Run clang-format

on: [push, pull_request]
#on:
#  pull_request:
#    types: [closed]

jobs:
  Clang-Format:
    #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}

    - uses: fish9167/clang-format-action@v2
      with:
        style: file
        
    - name: "Run if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run:
        git config --local user.name fish9167
        git config --local user.email 674821954@qq.com
        git add .
        git commit -m "Apply clang-format"
        git push --force --quiet "https://fish9167:${{ secrets.GITHUB_TOKEN }}@github.com/fish9167/test.git" ${{ github.head_ref }}:${{ github.head_ref }}
