# Name of the workflow
name: Clang-Format

# Controls when the action will run. Triggers the workflow on push for all branches
on: pull_request

# Defines the main job where we checkout our code, run clang-format
# and commit changes
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
    - uses: actions/checkout@v2

    # Applies clang-format to all C/C++ files w/ the specified style
    - name: Apply clang-format
      id: formatting
      uses: amete/clang-format-action@v0.2
      with:
        style: 'file'

    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
      
    - name: Get the output message
      run: echo "${{ steps.diff_files.outputs.message }}"
