name: Apply clang format

on:
  pull_request_target:
    types: [closed]


jobs:
  Clang-Format:
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}
        #ref: ${{ github.head_ref }}
        #ref: ${{ github.event.pull_request.head.ref }}
        #repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_sha }}
      
    - id: get_change_files
      uses: fish9167/file-changes-action@v1.2.3
      with:
        output: ' '
        fileOutput: ' '

    - name: get change files
      run: |
        cat $HOME/files.txt
        mv $HOME/files.txt ${{github.workspace}}/files.txt
    
    - uses: fish9167/clang-format-lint-action@master
      id: format
      with:
        exclude: .clang-format-ignore
        extensions: 'c,h,hpp,cpp,cxx'
        style: file
        inplace: True
      
    - name: Create Pull Request 
      uses: fish9167/create-pull-request@v3
      with:
          title: '[Bot] Automated PR to fix formatting errors'
          body: |
            Automated PR to fix formatting errors
          committer: fish0607 <yuj0607@163.com>
          author: fish0607 <yuj0607@163.com>
          commit-message: "[ci skip][AUTO]: Automated clang-format update: ${{ github.event.pull_request.head.sha }}  (#${{ github.event.number }})"
          #assignees: xxx,xxx
          #reviewers: xxx,xxx
          token: ${{ secrets.BOT_TOKEN }}
          push-to-fork: fish0607/test
          #base: ${{ github.base_ref }}
          # 对应的上传分支
          branch: t/bot/fix-format
          branch-suffix: short-commit-hash
          delete-branch: true
          milestone: 1

          
    #- uses: fish9167/git-auto-commit-action@v4
    #  with:
    #    commit_message: Apply clang-format
    #    #branch: ${{ github.head_ref }}
    #    branch: ${{ github.base_ref }}
    #    #commit_user_name: fish9767
    #    #commit_user_email: 674821954@qq.com
    #    #commit_author: fish9767<674821954@qq.com>
    #    push_options: --force