# Name of the workflow
name: Check Clang Format

#on: [push, pull_request]
on:
  pull_request: 
    types: [closed]

jobs:
  clang-format:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
      - uses: actions/checkout@v2

      # Applies clang-format to all C/C++ files w/ the specified style
      - name: Check clang-format
        uses: fish9167/clang-format-action@master
        id: formatting
        with:
          style: 'file'

      - name: Get the output message
        run: echo "${{ steps.formatting.outputs.message }}"
