name: Apply clang format

on:
  pull_request_target:
    types: [closed]


jobs:
  Clang-Format:
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}
        #ref: ${{ github.head_ref }}
        #ref: ${{ github.event.pull_request.head.ref }}
        #repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_sha }}

    
    - id: get_change_files
      uses: fish9167/file-changes-action@v1.2.3
      with:
        output: ' '
        fileOutput: ' '

    - name: get change files
      run: |
        cat $HOME/files.txt
        mv $HOME/files.txt ${{github.workspace}}/files.txt
    
    - uses: fish9167/clang-format-lint-action@master
      id: format
      with:
        exclude: .clang-format-ignore
        extensions: 'c,h,hpp,cpp,cxx'
        style: file
        inplace: True

    - name: Commit files
      run: |
        git config --local user.name "github-actions-clang-format[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git commit -a -m 'Automated clang-format update'
      continue-on-error: true
      
    - name: Create Pull Request 
      # 如果有格式化，才继续
      #if: steps.format.outputs.has-changes == 'true'
      uses: fish9167/create-pull-request@v3
      with:
          title: '[Bot] Automated PR to fix formatting errors'
          body: |
            Automated PR to fix formatting errors
          committer: fish0607 <yuj0607@163.com>
          #assignees: xxx,xxx
          #reviewers: xxx,xxx
          token: ${{ secrets.bot_token }}
          push-to-fork: fish0607/test
          #base: ${{ github.base_ref }}
          # 对应的上传分支
          branch: t/bot/fix-format
          branch-suffix: short-commit-hash
          delete-branch: true
          labels: |
            report
            automated pr
          
    #- uses: fish9167/git-auto-commit-action@v4
    #  with:
    #    commit_message: Apply clang-format
    #    #branch: ${{ github.head_ref }}
    #    branch: ${{ github.base_ref }}
    #    #commit_user_name: fish9767
    #    #commit_user_email: 674821954@qq.com
    #    #commit_author: fish9767<674821954@qq.com>
    #    push_options: --force
