name: change version

on: create
jobs:
  Change Version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_sha }}
    
    - name: change version
      run: |
        version=`cat ${{github.workspace}}/package.json | grep version`
        echo "Old Version: ${version}"
        new_version="\"version\": \"${{ github.head_sha }},"
        echo "New Version: ${new_version}"
        sed -i "s/${version=}/"version": "${{ github.head_sha }},""  ${{github.workspace}}/package.json
        
