name: change version

on: create
#on: push

jobs:
  Change-Package-Version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    #- uses: actions/setup-python@v2
    #  with:
    #    python-version: '3.7'
    
    #- name: change version
    #  run: |
    #    python ${{github.workspace}}/package.json ${{ github.head_ref }}
    - name: change
      run: |
        file=${{github.workspace}}/package.json
        branch=`${{github.ref}} | awk -F'v' '{print $2}'`
        old_version=`cat ${file} | grep version`
        new_version="\"version\": \"${branch"}\","
        echo "Old: ${old_version}
        echo "New: ${new_version}
        echo "Pachage.json File: ${file}"
        sed -i "s/${old_version}/${new_version}/g" ${file}
