name: change version

on: create
#on: push

jobs:
  Change-Package-Version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: change version
      run: |
        file=${{github.workspace}}/package.json
        branch=`echo ${{github.ref}} | awk -F'v' '{print $2}'`
        old_version=`cat ${file} | grep version`
        new_version="\"version\": \"${branch}\","
        echo "Old: ${old_version}
        echo "New: ${new_version}
        echo "Pachage.json File: ${file}"
        sed -i "s/${old_version}/${new_version}/g" ${file}
    - name: echo change result
      run: |
        cat ${{github.workspace}}/package.json | grep version
    - name: git push
      run: |
        git add package.json
        git commit -m "change version"
        git push ${{github.ref}}
